### PR TITLE
translation of Sharing State Between Components #357

### PR DESCRIPTION
**Pull request by Ehsan-Yari**
#357

### CODE REVIEW

**Comment by rezvani2647** [comment]
please remove unnecessarily ```div``` or any other tags and upadte this PR.
we should not add something to the file we only change then contents to farsi.
 
 thank you for your time. :-)

**Comment by Ehsan-Yari** [comment]
@rezvani2647 sorry about that.i thought i should wrap all paragraphs with div and give them RTL direction.
i removed all div containers and RTL styles as you said so my commit only contains the translation
thanks <3

**Comment by rezvani2647** [comment]
> @rezvani2647 sorry about that.i thought i should wrap all paragraphs with div and give them RTL direction. i removed all div containers and RTL styles as you said so my commit only contains the translation thanks <3

wonderful. 😍
Please, there's no need to sorry, you didn't do anything to sorry for. you've just done a great service. 🙏

**Review by rezvani2647 — APPROVED** [review]

**Comment by Ehsan-Yari** [comment]
@rezvani2647 thanks a lot.it was my pleasure to help

**Pull request merged**
